# Generated by Django 5.2.9 on 2025-12-09 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchase_purchaseitem_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0, help_text='Total en pesos chilenos'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(help_text='Precio unitario en pesos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(help_text='Costo en pesos chilenos', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Precio en pesos chilenos', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(default=0, help_text='Total en pesos chilenos'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='cost',
            field=models.IntegerField(help_text='Costo unitario al momento de la compra (en pesos)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.IntegerField(default=0, help_text='Total en pesos chilenos'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.IntegerField(help_text='Precio unitario al momento de la venta (en pesos)'),
        ),
    ]
