# Generated by Django 5.2.9 on 2025-12-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_total_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.CharField(default='Sin empresa', help_text='Nombre de la empresa suscrita', max_length=100),
        ),
    ]
