# Generated by Django 5.2.9 on 2025-12-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subscription_options_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.CharField(blank=True, help_text='Empresa/tenant dueña de esta sucursal', max_length=100, null=True),
        ),
    ]
